version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: payments-db
    environment:
      POSTGRES_DB: payments
      POSTGRES_USER: payments
      POSTGRES_PASSWORD: payments
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U payments"]
      interval: 10s
      timeout: 5s
      retries: 5

  payment-api:
    image: payment-api:local
    container_name: payment-api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PAYMENT_DB_URL: jdbc:postgresql://postgres:5432/payments
      PAYMENT_DB_USER: payments
      PAYMENT_DB_PASSWORD: payments
      PAYMENT_WORKER_BASE_URL: http://payment-worker:8090
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  payment-worker:
    image: payment-worker:local
    container_name: payment-worker
    depends_on:
      payment-api:
        condition: service_healthy
    environment:
      PAYMENT_API_BASE_URL: http://payment-api:8080
      WORKER_CPU_LOAD_MS: 500
      PAYMENT_WORKER_PORT: 8090
    ports:
      - "8090:8090"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8090/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
